### PR TITLE
Oracle WebLogic Domain 12.2.1 with ORDS configured and deployed on the AdminServer

### PR DESCRIPTION
**Pull request by lurodrig**
Image based on oracle/weblogic:12.2.1-developer. It creates a "Basic Server Domain" with the Oracle REST Data Services configured and deployed on the AdminServer.

The database used for this example is 12.2.0.1.0 standard edition. 

The README.md provides instructions on how to run and verify this image.

Signed-off-by: Luis Rodriguez Fernandez <luis.rodriguez.fernandez@cern.ch>

### CODE REVIEW

**Comment by brunoborges** [comment]
@gvenzl how this one compares to the upcoming ORDS image?

**Comment by lurodrig** [comment]
You are right, @brunoborges, from the point of view of the functionality (expose REST services from Oracle DB) it does not make any difference from the [OracleRestDataServices](https://github.com/cerndb/docker-images/tree/1221-domain-ords-autodeploy/OracleRestDataServices) . However, for us (CERN), an image like this is useful to debug.

**Comment by brunoborges** [comment]
Thanks for clarifying that @lurodrig. My conclusion is that while this is a great image for CERN's use, I am concerned that we will not be able to maintain two Dockerfiles with the same purpose.

If you decide to maintain thta Dockerfile on GitHub, we will be happy to link to it from our README.

**Comment by lurodrig** [comment]
Thanks @brunoborges! Sure, it makes sense: please feel free to add https://github.com/cerndb/oracle-weblogic-1221-domain-ords-autodeploy to your README.

**Pull request closed without merging**
