### PR TITLE
Fixed shellcheck issues in the script

### PR DESCRIPTION
**Pull request by tanmaygarg-oracle**

### CODE REVIEW

**Review by rishiagarwal-oracle — APPROVED** [review]
LGTM!

**Comment by tanmaygarg-oracle** [comment]
@Djelibeybi We have taken care of the shellcheck issues. Please review and merge.

**Review by rishiagarwal-oracle — DISMISSED** [review]
LGTM!

**Review by rishiagarwal-oracle — APPROVED** [review]
LGTM

**Pull request merged**
