### PR TITLE
Added scripts for Oracle EBS HRMS

### PR DESCRIPTION
**Pull request by tanmaygarg-oracle**

### CODE REVIEW

**Comment by rishiagarwal-oracle** [comment]
Please fix the issues reported by shellcheck

**Comment by tanmaygarg-oracle** [comment]
@rishiagarwal-oracle fixed the linter. Only infos are appearing now in the report.

**Comment by Djelibeybi** [comment]
Also, please rebase your branch.

**Comment by Djelibeybi** [comment]
Also, why is this being submitted to this repo? All I see are SQL files. There's no documentation or a Dockerfile or anything to tell me what all this is for.

**Comment by Djelibeybi** [comment]
I've switched this to draft mode so that you can provide documentation and context as to why these files belong in this repo, because right now it seems like they would be better suited for a sample repo, not this one.

**Review by rishiagarwal-oracle — APPROVED** [review]
LGTM !

**Comment by Djelibeybi** [comment]
My concern is duplication of distribution: I'd rather additional documentation be added to explain how to find and download these files from OTN, so that they don't have to be maintained in both locations. Whenever content is duplicated, it generally drifts out of date/sync and thus results in user issues/imcompatibility.

Is there a reason why this can't just be documented as above? Or if this is documented already on docs.oracle.com, a link added for users to follow who want to use these files?

**Comment by rishiagarwal-oracle** [comment]
@Djelibeybi with containers, we are trying to make the customer experience better. The old approach is very cumbersome for customers. They have to manually download from OTN and extract files and run them. With the new approach it will work in a seamless, automated fashion for customers. 

We are enforcing internal process to make sure, things are always pushed to both the delivery channels.

**Comment by Djelibeybi** [comment]
Fair enough and I'm glad to hear about the internal process. 

Is it possible to at least add some documentation that explains what these files are for and when they're used?

**Comment by rishiagarwal-oracle** [comment]
@Djelibeybi agreed
@tanmaygarg-oracle please add a readme in the scripts folder stating the purpose of these files

**Comment by tanmaygarg-oracle** [comment]
@Djelibeybi I have added the read me stating the purpose of the scripts

**Comment by Djelibeybi** [comment]
I've sent a review request to @rishiagarwal-oracle. Once they approve the PR, I'll merge it.

**Review by rishiagarwal-oracle — APPROVED** [review]
LGTM!

**Pull request merged**
