### PR TITLE
Preventing undesired exit on failure to remove dangling images

### PR DESCRIPTION
**Pull request by aditya059**
Preventing undesired exit on failure to remove dangling images in buildContainerImage.sh file

### CODE REVIEW

**Review by yunus-qureshi — DISMISSED** [review]

**Comment by aditya059** [comment]
@gvenzl The lint error are not related to my changes. Please approve and merge.

**Comment by gvenzl** [comment]
Hi @aditya059, I cannot bypass the lint errors which are preventing the merge.
Looking at the output, these seem to be 3 simple fixes and it might be the easiest to just add these into this merge.

Please let me know whether that's a possibility.

**Comment by aditya059** [comment]
@gvenzl 
Fixed. Please merge

**Review by gvenzl — APPROVED** [review]

**Comment by gvenzl** [comment]
Great, thank you @aditya059!

**Pull request merged**
