### PR TITLE
Issue-388 - Added support to execute scripts after database is up

### PR DESCRIPTION
**Pull request by jcustenborder**
Added support to launch scripts during startup.

### CODE REVIEW

**Comment by Djelibeybi** [comment]
@brunoborges can you follow-up with OCA requirements? I like this enhancement. :)

**Comment by brunoborges** [comment]
@jcustenborder can you please [sign this](http://www.oracle.com/technetwork/community/oca-486395.html) and when you email to Oracle, please cc me (bruno dot borges at oracle dot com)

**Comment by jcustenborder** [comment]
@brunoborges Hah my scanner didn't want to work the other day and I forgot. I have it signed sitting in the scanner. I set a reminder to do it when I get home tonight. Are there any other changes that are required?

**Comment by brunoborges** [comment]
I don't think so.

**Comment by nicolimo86** [comment]
Shouldn't be documented this functionality? I mean in the README.

**Comment by NMichas** [comment]
We'd love to see this being merged!

**Comment by jcustenborder** [comment]
@brunoborges Sorry about the delay. I've been traveling then my scanner was having issues. I emailed you something.

**Comment by jcustenborder** [comment]
Sorry for the delay on this. I was told I need to change one thing on the
scanned paperwork I sent Oracle. Unfortunately I'm on holiday until the
12th with limited access to the internet.

**Comment by gvenzl** [comment]
No rush, enjoy your holiday! Once you are back we can take a look at this which is convenient for me as well because I too am traveling at the moment, albeit not for holiday :(

**Comment by brunoborges** [comment]
@jcustenborder your OCA was accepted. We are ready to take this in, but can you check @gvenzl's comments?

**Comment by jcustenborder** [comment]
@brunoborges Just saw this. Will do now.

**Comment by jcustenborder** [comment]
@gvenzl Sorry about missing your comments. Can you let me know if this is what you are looking for?

**Comment by jcustenborder** [comment]
@gvenzl Comming back around on this one. Are there any other changes you need from me?

**Comment by gvenzl** [comment]
Hi @jcustenborder, thanks a lot for your contribution. I have tested your changes and they work fine.

Just minor comments:

* After about 5 times having typos typing /docker-entrypoint-initdb.d I thought it may be better to keep it in sync with the other volume `/opt/oracle/oradata` and just use `/opt/oracle/scripts` instead. I think it just will be easier for folks to remember, please let me know your thoughts.
* I amended the example that you have in the ReadMe slightly as Docker does require an absolute path to a host mounted volume and because the password at this stage is auto generated and not known to the user if not specified directly.
* The XE version did actually not work due to the way how XE is run (under the root user rather than oracle)

Furthermore, I have added a hopefully simple to follow sample.

You can have a look at the changes here: https://github.com/oracle/docker-images/compare/389-startupscripts

If you agree with the changes I will file a PR containing yours and those and merge those back into the master.

Please let m know your thoughts.

**Comment by jcustenborder** [comment]
> After about 5 times having typos typing /docker-entrypoint-initdb.d I thought it may be better to keep it in sync with the other volume /opt/oracle/oradata and just use /opt/oracle/scripts instead. I think it just will be easier for folks to remember, please let me know your thoughts.

I used /docker-entrypoint-initdb.d because this is a standard location. MySQL and Postgres use this location. I was trying to keep things consistent.  

> The XE version did actually not work due to the way how XE is run (under the root user rather than oracle)

Thanks for catching this. Are there any changes you recommend?

**Comment by gvenzl** [comment]
I see, in that case it may makes sense to either keep that or perhaps just look in both directories. I'm also starting to think whether we don't need to separate setup and startup scripts. Right now, there is no way to run a script only at the setup time of the database but not when restarting it unless you put some logic into your scripts.

Just a slight change needed using the `su` command, check https://github.com/oracle/docker-images/compare/389-startupscripts#diff-c7ba2f7176dd4e0d1f80615d2a83067bR142

**Comment by Djelibeybi** [comment]
My (unrequested/unwarranted) opinion: I prefer `/docker-entrypoint-initdb.d` for the same reason @jcustenborder mentioned: it's already in use by both MySQL and PostgreSQL.

And I think separating the scripts into setup (i.e. first-run when the DB is initially created) and startup makes excellent sense too.

**Comment by gvenzl** [comment]
Indeed, but at that point the path will become inconsistent with MySQL and Postgres anyway. Probably still best to keep both and search for both, e.g. if `/docker-entrypoint-initdb.d` does not exist/is empty, search for `/opt/oracle/scripts` or something like that. Best of both worlds.

**Comment by jcustenborder** [comment]
@gvenzl Did you want to add this or did you want me to do it?

**Comment by gvenzl** [comment]
@jcustenborder, I'm happy to make the changes if that is fine with you.

**Comment by jcustenborder** [comment]
Works for me!

**Comment by gvenzl** [comment]
@jcustenborder, I have filed a new PR #471 which incorporates your contributions as well as the changes discussed.

**Comment by gvenzl** [comment]
Closing this PR in favor of #471. Thanks a lot for your contribution, @jcustenborder! Very much appreciated!

**Pull request closed without merging**
