### PR TITLE
Support OracleLinux 8

### PR DESCRIPTION
**Pull request by carstenartur**

### CODE REVIEW

**Comment by yunus-qureshi** [comment]
OL7 is the base development platform for 21c and it is certified on OL7. 
OL7 containers should work on OL8 hosts too. I don't see a valid reason for this PR

**Comment by carstenartur** [comment]
> OL7 is the base development platform for 21c and it is certified on OL7. 
> 
> OL7 containers should work on OL8 hosts too. I don't see a valid reason for this PR

Ah, ok. I changed it because the ol7 variant did not work for me and after I applied the changeit started to work.

**Comment by yunus-qureshi** [comment]
It is working for me on OL8

**Comment by carstenartur** [comment]
> It is working for me on OL8
Did you really try to build an run the docker image in question?
Sorry for asking, just to be sure...

**Comment by yunus-qureshi** [comment]
Yes, using Podman on OL8

**Comment by carstenartur** [comment]
I wonder how you worked around the error regarding iputils:

...
  tcp_wrappers.x86_64 0:7.6-77.el7                                              
  tcp_wrappers-libs.x86_64 0:7.6-77.el7                                         
  unzip.x86_64 0:6.0-24.el7_9                                                   
  util-linux.x86_64 0:2.23.2-65.0.3.el7_9.1                                     
  xorg-x11-utils.x86_64 0:7.5-23.el7                                            
  xorg-x11-xauth.x86_64 1:1.0.9-1.el7                                           
  xz.x86_64 0:5.2.2-1.el7                                                       

Dependency Updated:
  glibc.x86_64 0:2.17-326.0.1.el7_9                                             
  glibc-common.x86_64 0:2.17-326.0.1.el7_9                                      
  libcom_err.x86_64 0:1.42.9-19.0.1.el7                                         

Failed:
  iputils.x86_64 0:20160308-10.el7                                              

Complete!
Removing intermediate container 14f99ce6d436
The command '/bin/sh -c chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     cd $INSTALL_DIR &&     yum -y install expect &&     $INSTALL_DIR/$SETUP_LINUX_FILE &&     chown -R oracle:oinstall $ORACLE_BASE /home/oracle &&     sed -i -e 's/\(oracle\s\+hard\s\+nofile\)/# \1/' /etc/security/limits.d/oracle-database-preinstall-21c.conf &&     unbuffer yum -y install $INSTALL_FILE_1 &&     yum -y remove expect &&     rm -rf /var/cache/yum &&     rm -rf /var/tmp/yum-* &&     mv $INSTALL_DIR/$CONF_FILE /etc/sysconfig/ &&     cd $HOME &&     rm -rf $INSTALL_DIR &&     $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh' returned a non-zero code: 1

ERROR: Oracle Database container image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the build operation.

This error occurs when you try to build using OL7 because of this:

https://docs.oracle.com/en/operating-systems/oracle-linux/7/relnotes7.9/ol7-known-issues.html#ol7-bug-25024258

**Comment by yunus-qureshi** [comment]
I am not seeing this error. May be your container root is on NFS as the above link says

**Comment by carstenartur** [comment]
I'm not exactly sure what you mean by this. However, this is how I start the build:

export BUILDAH_FORMAT=docker
export BUILDAH_ISOLATION=chroot
./buildContainerImage.sh -i -x -v 21.3.0 -t oracle/database:21-onprem -o '--build-arg INSTALL_FILE_1=db_home_2022-04-26_09-11-50AM.zip'

Maybe the issue mentioned in the release notes of OracleLinux 7.9 is exactly the same (the error message is) when using "aufs" within docker?
https://docs.docker.com/storage/storagedriver/aufs-driver/

...
  Installing : kmod-20-28.0.3.el7.x86_64                                 75/127 
  Installing : elfutils-libs-0.176-5.el7.x86_64                          76/127 
  Installing : systemd-libs-219-78.0.7.el7_9.5.x86_64                    77/127 
  Installing : 1:dbus-libs-1.10.24-15.0.1.el7.x86_64                     78/127 
  Installing : systemd-219-78.0.7.el7_9.5.x86_64                         79/127 
Failed to get D-Bus connection: Operation not permitted
  Installing : elfutils-default-yama-scope-0.176-5.el7.noarch            80/127 
  Installing : 1:dbus-1.10.24-15.0.1.el7.x86_64                          81/127 
  Installing : crontabs-1.11-6.20121102git.el7.noarch                    82/127 
  Installing : cronie-anacron-1.4.11-24.el7_9.x86_64                     83/127 
  Installing : cronie-1.4.11-24.el7_9.x86_64                             84/127 
  Installing : systemd-sysv-219-78.0.7.el7_9.5.x86_64                    85/127 
  Installing : rpcbind-0.2.0-49.el7.x86_64                               86/127 
  Installing : sysstat-10.1.5-19.0.3.el7.x86_64                          87/127 
  Installing : ksh-20120801-143.0.1.el7_9.x86_64                         88/127 
  Installing : gssproxy-0.7.0-30.el7_9.x86_64                            89/127 
  Installing : iputils-20160308-10.el7.x86_64                            90/127Error unpacking rpm package iputils-20160308-10.el7.x86_64
 
error: unpacking of archive failed on file /usr/bin/ping;6298d76d: cpio: cap_set_file
error: iputils-20160308-10.el7.x86_64: install failed
  Installing : initscripts-9.49.53-1.0.3.el7_9.1.x86_64                  91/127 
  Installing : net-tools-2.0-0.25.20131004git.el7.x86_64                 92/127 
  Installing : 1:smartmontools-7.0-2.el7.x86_64                          93/127 
  Installing : libcgroup-0.41-21.el7.x86_64                              94/127 
  Installing : openssh-7.4p1-22.0.1.el7_9.x86_64                         95/127 
  
  However, as changing the Dockerfile to OracleLinux8 as in this PullRequest solves the problem for me that is good enough.
  Best regards,
  Carsten

**Pull request closed without merging**
