### PR TITLE
DB crash when container is killed/stopped before DB is ready .

### PR DESCRIPTION
**Pull request by Mahi0911**
If one of the database pods which is initialising database , is killed/stopped before it's ready , the other pods try to create the database and result in Pod Crash  #1969 
Solved this by creating a checkpoint file and checking if it is present before creating or starting database.

### CODE REVIEW

**Comment by Mahi0911** [comment]
#1971

**Comment by Mahi0911** [comment]
Addressed the issue #1972 by changing permissions of "`$ORACLE_BASE/scripts/extensions/setup/*.sh`" file

**Review by yunus-qureshi — APPROVED** [review]
Looks fine, thanks

**Review by gvenzl — APPROVED** [review]

**Comment by gvenzl** [comment]
Awesome, thanks @Mahi0911!

**Pull request merged**
