### PR TITLE
feat(developper): Add oracledb flavor for python 3.8/3.9 on OL8

### PR DESCRIPTION
**Pull request by AmedeeBulle**
Signed-off-by: Philippe Vanhaesendonck <philippe.vanhaesendonck@oracle.com>

### CODE REVIEW

**Comment by Djelibeybi** [comment]
Sorry, but our approval to distribute these images is based on only installing software as RPMs from yum.oracle.com. We are not allowed to use `pip` to install packages.

**Comment by AmedeeBulle** [comment]
Yes, I was thinking about that as well.

Most python developers will have cx_oracle as dependency in their `requirement.txt` or `setup.py`  together with their other dependencies.

So it might make sense to publish with the IC, but without CxO.

But we need to be clear on what we publish to avoid confusion between the the projects with or without CxO...

**Comment by Djelibeybi** [comment]
We already have an Instant Client image that folks can add any language they like on top of. I do not want to publish language-specific images that do not include the language specific driver for Oracle DB.

**Comment by cjbj** [comment]
@Djelibeybi you already have a [lot of language specific images](https://github.com/oracle/docker-images/tree/main/OracleLinuxDevelopers) that don't have the Oracle DB driver, so I assume you mean "language specific, with Instant Client, but without the DB driver".

**Comment by Djelibeybi** [comment]
Yes, that's what I meant. Thanks @cjbj

**Pull request closed without merging**
