### PR TITLE
Update hostname in runOracle.sh and configTcps.sh

### PR DESCRIPTION
**Pull request by viragtripathi**
Resolution for hostname command not found.

### CODE REVIEW

**Comment by yunus-qureshi** [comment]
@viragtripathi please clarify if this for the ARM64 image?

**Comment by viragtripathi** [comment]
> @viragtripathi please clarify if this for the ARM64 image?

@yunus-qureshi yes this is for the ARM64 image and I think we should also check for arch type then apply the hostname fix for arm64.

**Comment by yunus-qureshi** [comment]
> > @viragtripathi please clarify if this for the ARM64 image?
> 
> @yunus-qureshi yes this is for the ARM64 image and I think we should also check for arch type then apply the hostname fix for arm64.

Thanks @viragtripathi we are going fix this differently. @aditya059 will raise a PR. Thanks

**Comment by viragtripathi** [comment]
> > > @viragtripathi please clarify if this for the ARM64 image?
> > 
> > 
> > @yunus-qureshi yes this is for the ARM64 image and I think we should also check for arch type then apply the hostname fix for arm64.
> 
> Thanks @viragtripathi we are going to fix this differently. @aditya059 will raise a PR. Thanks

Sounds good @yunus-qureshi. Thanks for the quick response.

**Comment by aditya059** [comment]
This issue will be fixed as part of PR #2666

**Pull request closed without merging**
