### PR TITLE
managed server listen address is always set to IP

### PR DESCRIPTION
**Pull request by aquasheep20**
When a managed server is created, the listen address is always set to IP address.  This occurs even if the MS_HOST variable is passed.  The behavior can be observed in the WebLogic console.  A problem can arise if the managed server container is restarted and it does not get the same IP.  The result is the managed server will not start.  To fix this the and add-server.py script is updated to set listen address as hostname when the MS_HOST variable is passed.  (the host name should be passed as the container name).  The container IP will be resolved as long as the default docker bridge is not being used.  The existing behavior is unchanged when MS_HOST is not passed,  mshost defaults to msinternal

### CODE REVIEW

**Comment by brunoborges** [comment]
@mriccell, mind to take a look at this? If possible test it too?

**Comment by mriccell** [comment]
This change looks good!  @aquasheep20 Thank you so much for contributing!

**Comment by mriccell** [comment]
I looked at the 1213-domain image and in the Dockerfile there is no way for a user to pass in the MS_HOST name.  The MS_HOST should be set in the ENV of the Dockerfile.

**Comment by aquasheep20** [comment]
file removed 
-MZ

**Comment by brunoborges** [comment]
Once @mriccell approves, we merge.

**Pull request merged**
