### PR TITLE
Minor improvements to the shell scripts for oracle database configs

### PR DESCRIPTION
**Pull request by Ma27**
* Use `/usr/bin/env bash` to avoid issues on distros that don't provide
  `/bin/bash` (e.g. NixOS).
* Give a hint how to increase storage-size in dockerd
  if the space-check fails.

### CODE REVIEW

**Comment by Djelibeybi** [comment]
I don't understand why you're changing the scripts that run inside the containers: we know what's inside the containers and it will always contain `/bin/bash` so this change is unnecessary.

**Comment by Ma27** [comment]
My mistake - I did a `sed`, although this was only relevant for `buildDockerImage.sh`, sorry!
Will fix that tomorrow :)

**Comment by Djelibeybi** [comment]
I'm going to close this pull request because it has 170 modified files and you probably only need to modify a handful. Likewise, I think that storage test should also be done in `buildDockerImage.sh` because you can determine storage driver externally and warn accordingly.

**Comment by Djelibeybi** [comment]
Please do submit a new PR with an updated commit, though. And in the new PR, can you also confirm whether you've signed the Oracle Contributor Agrement at https://www.oracle.com/technetwork/community/oca-486395.html -- if not, please do sign and submit that before opening the new PR as outlined in the contribution guide for this repo.

**Pull request closed without merging**
