### PR TITLE
load env var agent java options from java.options

### PR DESCRIPTION
**Pull request by drupanchal**
Signed-off-by: Drupad Panchal <drupad.panchal@oracle.com>

### CODE REVIEW

**Review by ChaitanyaKulkarni28 — DISMISSED** [review]

**Review by niravg75 — APPROVED** [review]

**Comment by Djelibeybi** [comment]
Please resolve the issues raised by the shell script linter.

**Review by Djelibeybi — CHANGES_REQUESTED** [review]
The shell script linter issues need to be resolved.

**Comment by Djelibeybi** [comment]
I suspect a lot of the linter issues are due to the missing shebang line, i.e. if you add `#!/bin/bash` as the first line of each script, the linter will know to lint the script for use with `bash` and not `sh`.

**Comment by Djelibeybi** [comment]
I see the linter is passing now, which is great. Thanks for your effort on this! Once you're happy, please set the PR out of draft mode so it can be merged. You may have to re-request a review from me so that I can resolve the request for changes.

**Review by Djelibeybi — APPROVED** [review]

**Comment by Djelibeybi** [comment]
Either @ChaitanyaKulkarni28 or @niravg75 must also approve as they are the codeowners.

**Review by niravg75 — APPROVED** [review]

**Pull request merged**
