### PR TITLE
1213 domain cgiservlet

### PR DESCRIPTION
**Pull request by lurodrig**
The purpose of this sample is to help our devops people to debug issues related with this servlet (e.g. 3-14340994281).

### CODE REVIEW

**Comment by Djelibeybi** [comment]
Ping @mriccell to review this PR.

**Comment by Djelibeybi** [comment]
This PR seems to have stalled. 

@lurodrig have you signed an OCA: http://www.oracle.com/technetwork/community/oca-486395.html

@mriccell can you please review this PR?

**Comment by lurodrig** [comment]
Hello @Djelibeybim,

mmm, nope I did not sign it. I will the and let you know

Cheers,

Luis

**Comment by mriccell** [comment]
Thanks Luis for submitting this PR, it looks good.

**Comment by Djelibeybi** [comment]
Thanks @mriccell. Once the OCA is signed, I'll merge this PR.

**Comment by mriccell** [comment]
@lurodrig can you please sign OCA so that we can merge your changes?

**Comment by Djelibeybi** [comment]
I am closing this PR due to lack of CLA submission.

**Pull request closed without merging**
