### PR TITLE
Changed for handling already upgrade in progress, changed frequency o…

### PR DESCRIPTION
**Pull request by tanmaygarg-oracle**
…f cron and added command to upgrade without providing agent package

### CODE REVIEW

**Comment by rishiagarwal-oracle** [comment]
Please resolve shellcheck issues in the new code

**Review by rishiagarwal-oracle — APPROVED** [review]
LGTM !

**Review by rishiagarwal-oracle — APPROVED** [review]
LGTM !

**Review by rishiagarwal-oracle — APPROVED** [review]
LGTM !

**Review by Djelibeybi — CHANGES_REQUESTED** [review]
Please resolve the linter issues.

**Review by Djelibeybi — APPROVED** [review]

**Pull request merged**
