### PR TITLE
Document setting Oracle Database single instance resource limits

### PR DESCRIPTION
**Pull request by marcinroman**
This change adds documentation of setting ulimits for single instance docker run command.

### CODE REVIEW

**Comment by aditya059** [comment]
Hi @marcinroman 

Can you tell me why are these parameters needed? I think these are taken care by oracle's preinstalled rpm. Are you facing any issues without these parameters?

**Comment by marcinroman** [comment]
These  preinstalled container settings doesn't seem to affect limits.
If run docker-compose without ulimit arguments then: 
```
[oracle@test ~]$ cat /etc/security/limits.d/oracle-rdbms-server-12cR1-preinstall.conf 

# oracle-rdbms-server-12cR1-preinstall setting for nofile soft limit is 1024
oracle   soft   nofile    1024

# oracle-rdbms-server-12cR1-preinstall setting for nofile hard limit is 65536
oracle   hard   nofile    65536

# oracle-rdbms-server-12cR1-preinstall setting for nproc soft limit is 16384
# refer orabug15971421 for more info.
oracle   soft   nproc    16384

# oracle-rdbms-server-12cR1-preinstall setting for nproc hard limit is 16384
oracle   hard   nproc    16384

# oracle-rdbms-server-12cR1-preinstall setting for stack soft limit is 10240KB
oracle   soft   stack    10240

# oracle-rdbms-server-12cR1-preinstall setting for stack hard limit is 32768KB
oracle   hard   stack    32768

# oracle-rdbms-server-12cR1-preinstall setting for memlock hard limit is maximum of 128GB on x86_64 or 3GB on x86 OR 90 % of RAM
oracle   hard   memlock    134217728

# oracle-rdbms-server-12cR1-preinstall setting for memlock soft limit is maximum of 128GB on x86_64 or 3GB on x86 OR 90% of RAM
oracle   soft   memlock    134217728
[oracle@test ~]$ ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 96216
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
[oracle@test ~]$ ulimit -aH
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 96216
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

See:
https://stackoverflow.com/questions/24318543/how-to-set-ulimit-file-descriptor-on-docker-container-the-image-tag-is-phusion

**Review by aditya059 — APPROVED** [review]
Hi @marcinroman 

Yes, you are correct. Approved.

Thanks

**Comment by aditya059** [comment]
Hi @gvenzl 

I tested this. Its correct. You can approve and merge.

**Review by yunus-qureshi — APPROVED** [review]

**Review by gvenzl — APPROVED** [review]

**Comment by gvenzl** [comment]
Thanks a lot for your contribution, @marcinroman!

We really appreciate it!

**Pull request merged**
