### PR TITLE
Add domain with admin port enabled

### PR DESCRIPTION
**Pull request by amyroh**

### CODE REVIEW

**Comment by Djelibeybi** [comment]
@amyroh sorry for the delay. I will ping @mriccell and @brunoborges to review this PR as soon as possible.

**Comment by amyroh** [comment]
I've updated Dockerfile/README and did the following steps - 

bash-4.2$ git merge upstream/master
Already up-to-date.
bash-4.2$ git checkout adminport
Switched to branch 'adminport'
bash-4.2$ git rebase master
Current branch adminport is up to date.
bash-4.2$ git checkout
bash-4.2$ git rebase -i master
Successfully rebased and updated refs/heads/adminport.
bash-4.2$ git status
# On branch adminport
nothing to commit, working directory clean

Do I need to create another pull request?

**Comment by brunoborges** [comment]
Is this sample really needed? Seems to me more of a WLST example. Maybe if we just added the lines that enable admin port into the basic sample, maybe commented, would be sufficient.

**Comment by mriccell** [comment]
@amyroh  Bruno is correct, why do you not merge these changes into the already existing 12212-domain sample.

**Comment by brunoborges** [comment]
This PR should enhance existing samples.

**Pull request closed without merging**
