### PR TITLE
Supporting oracle database 19c EE on linux arm64 platforms

### PR DESCRIPTION
**Pull request by aditya059**
This PR is for supporting oracle database 19c EE on linux arm64 platforms.

### CODE REVIEW

**Review by gvenzl — APPROVED** [review]

**Comment by lscoughlin** [comment]
does this mean we're going to se an aarch64 image on container-registry.oracle.com?  Because _that_ would really be the bees knees.

**Comment by yunus-qureshi** [comment]
@lscoughlin 

it is already available
container-registry.oracle.com/database/enterprise:19.19.0.0

**Comment by ivang-orcl** [comment]
is there any plan to support this on RAC? `OracleDatabase/RAC/*/dockerfiles/buildContainerImage.sh`

**Comment by shahabganji** [comment]
@yunus-qureshi is there also anything for the express/free edition?

**Pull request merged**
