### PR TITLE
NoSQL update

### PR DESCRIPTION
**Pull request by Djelibeybi**
This commit cleans up the `VOLUME` support by separating the `/kvroot` and turning that into a volume. This means the data itself can persist an upgrade of the NoSQL binaries.

### CODE REVIEW

**Comment by Djelibeybi** [comment]
Note this requires #381 to be merged first.

**Comment by Djelibeybi** [comment]
@nirmay can you please review this and see if it's more aligned with what you wanted to achieve with your previous PR?

**Comment by Djelibeybi** [comment]
Ok, have squashed all the changes so that only the `Dockerfile` diff requires review.

**Comment by brunoborges** [comment]
It's fine by me.

**Comment by Djelibeybi** [comment]
I will wait for @nirmay to comment/review to make sure I'm meeting his expectations for `VOLUME` support.

**Comment by nirmay** [comment]
Thanks @Djelibeybi for taking the time to make these changes, this is a better approach.

**Pull request merged**
