### PR TITLE
Wcp 30899 readme fix

### PR DESCRIPTION
**Pull request by anandsirasagi**
Updated Readme With Correct Year

### CODE REVIEW

**Comment by Djelibeybi** [comment]
If you're editing the copyright line anyway, please remove `All rights reserved.` as Oracle no longer uses that phrase.

**Comment by Djelibeybi** [comment]
Also, please remember to rebase your fork so that we don't get the previous commits in your branch.

**Review by Djelibeybi — APPROVED** [review]

**Comment by Djelibeybi** [comment]
My comments are not merge blockers, btw. Which is why I've approved it. You can chose to fix or not, up to you. If you want to fix later, @dgothe can approve and I'll merge it.

**Review by Djelibeybi — APPROVED** [review]

**Comment by Djelibeybi** [comment]
Still waiting for @dgothe to approve as code owner.

**Review by dgothe — APPROVED** [review]

**Pull request merged**
