### PR TITLE
Compose File Changes

### PR DESCRIPTION
**Pull request by saurabhaahujaa**

### CODE REVIEW

**Review by psaini79 — APPROVED** [review]

**Comment by Djelibeybi** [comment]
Please rebase your branch so it's in sync with the `main` branch of this repo.

**Comment by saurabhaahujaa** [comment]
@Djelibeybi Rebase is completed.

**Comment by Djelibeybi** [comment]
@saurabhaahujaa great. I'll do a full review on Monday.

**Comment by Djelibeybi** [comment]
In the meantime, you may want to squash your commits down to a single commit to make the rebase merge a single commit instead of nine.

**Comment by saurabhaahujaa** [comment]
Squashing commits closed the pull request, so opened new one https://github.com/oracle/docker-images/pull/2749

**Pull request closed without merging**
