### PR TITLE
Remove yum install util-linux

### PR DESCRIPTION
**Pull request by mriccell**
Remove yum install util-linux and remove su to make image as small as possible.
Move common commands to the head of Dockerfiles to reutilize layers across different WLS version images.
Standardize the use of port numbers, admin port 7001, managed server port 7002

### CODE REVIEW

**Comment by Djelibeybi** [comment]
I suggest a few minor tweaks:

- Update `12.2.1/Dockerfile.infrastructure` as well
- Move the "Setup filesystem and oracle user" section in all the `Dockerfiles` to after the `MAINTAINER` directive so that the layer created will be shared between all WLS images.

The second one means that you need to add this block at the top of the `Dockerfile` across all versions:

```
RUN chmod a+xr /u01 && \
    useradd -b /u01 -m -s /bin/bash oracle && \
    echo oracle:oracle | chpasswd && \
    chown oracle:oracle -R /u01 
```

It also means you'll have to add a new `RUN` directive later to `chmod +xr $SCRIPT_FILE` after you copy in the `$SCRIPT_FILE`.

**Comment by Djelibeybi** [comment]
LGTM. Thoughts from @brunoborges or @gvenzl?

**Comment by mriccell** [comment]
@Djelibeybi @brunoborges @gvenzl I am in the process of testing these images

**Comment by Djelibeybi** [comment]
I've asked @mriccell to squash all these commits so that our review is a bit simpler.

**Comment by mriccell** [comment]
@Djelibeybi  @brunoborges @gvenzl I have squash the commits and they are ready for review

**Comment by gvenzl** [comment]
LGTM

**Comment by Djelibeybi** [comment]
Merged. Thanks @mriccell :)

**Pull request merged**
