### PR TITLE
Initial release of OUD on docker for oracle/docker-images

### PR DESCRIPTION
**Pull request by oehrlis**
Hi

According to #656 I did create a simple initial release of Oracle Unified Directory on docker. Currently just OUD 12.2.1.3.0 base release with a standalone OUD is included. Build and use of OUD on docker is documented in README.md.

Currently the docker image has to be build using _docker build_ a _buildDockerImage.sh_ is not yet ready.

Signed-off-by: Stefan Oehrli <stefan.oehrli@trivadis.com>

### CODE REVIEW

**Comment by Djelibeybi** [comment]
It's going to take me a bit of time to find someone to review this, because I know nothing about OUD.

**Comment by oehrlis** [comment]
Ok, in the meanwhile I may finish the buildDockerImage.sh

**Comment by Djelibeybi** [comment]
I have the product management team for OUD reviewing your submission and evaluating against some of their internal/non-production builds.

**Comment by oehrlis** [comment]
Sofar I‘ve just checked in plain oud 12.2.1.3.0. I do also have 12.2.1.3 with the latest bundle patch, oudsm or oud 11g. oud pm should let me know if my build needs to be adjusted. A possible concern could be, that i do not use the default oud instance name asinst1. I use a named instance which is put on a volume if available.

**Comment by Djelibeybi** [comment]
Merged after internal review by OUD. Thank you very much for your contribution (and patience).

**Pull request merged**
