### PR TITLE
Updated Lint checked Version OracleTuxedo22c in Unarchive

### PR DESCRIPTION
**Pull request by samil786**
Created new Folder for Oracle Tuxedo and copied files for Tuxedo 22c Version.

### CODE REVIEW

**Review by Djelibeybi — CHANGES_REQUESTED** [review]
This PR needs to be restructed to meet our contribution guidelines:

1. Please rename the `OracleTuxedo\docker-images\` directory to `OracleTuxedo\container-images\`. 
2. Please remove the `OracleTuxedo\.github\` directory entirely. 
3. Please remove the `OracleTuxedo\docker-images\Archive\OracleTuxedo` directory and move that content up to the `OracleTuxedo\container-images\Archive\` directory.
4. We don't store Helm charts in this repository. Please remove those from this PR and submit them to the https://github.com/oracle/helm-charts repository instead.

**Comment by Djelibeybi** [comment]
Keep in mind that all the content you're moving doesn't meet our current contribution guidelines either. I haven't done an actual review, but none of the copyright headers are correct and the documentation uses terms and phrases that are no longer acceptable due to inappropraite use of registered trademarks. 

As mentioned before, if you want to move that content out of the archive, you will need to update it to meet our current standards.

**Comment by Diw-dev** [comment]
> none of the copyright headers are correct and the documentation uses terms and phrases that are no longer acceptable due to inappropraite use of registered trademarks.

Hello Djelibeybi,
Could you please give us some tips on which section of the copyright header is not correct ? We would like to correct it.

**Comment by samil786** [comment]
Updated Oracle Tuxedo in Archive with Tuxedo22c and deleted Oracle Tuxedo 22c from unarchive

**Comment by Djelibeybi** [comment]
The Tuxedo 22c stuff is updated so that shouldn't be in the archive. That content can move back to an OracleTuxedo directory in the root. 

Along with that, please carefully review the [contribution guide](https://github.com/oracle/docker-images/blob/main/CONTRIBUTING.md) and ensure that your content meets the requirements of that guide. In particular, please review the documentation rules and remove all use of the word Docker except when specifically demonstrating the use of the `docker` client.

**Comment by Djelibeybi** [comment]
Your files are all missing copyright headers too, so those need to be inserted at the top of your `Dockerfile` and shell scripts. The copyright header should adhere to the short reference format of the UPL, as documented here: https://opensource.oracle.com/licenses/upl/#faq-7

**Comment by samil786** [comment]
Moved the OracleTuxedo22c to the root and made changes as mentioned.

**Comment by Diw-dev** [comment]
> The Tuxedo 22c stuff is updated so that shouldn't be in the archive. That content can move back to an OracleTuxedo directory in the root.
> 
> Along with that, please carefully review the [contribution guide](https://github.com/oracle/docker-images/blob/main/CONTRIBUTING.md) and ensure that your content meets the requirements of that guide. In particular, please review the documentation rules and remove all use of the word Docker except when specifically demonstrating the use of the `docker` client.

Hello Djelibeybi,

Thanks for all your help. We have incorporated the Copyright and UPL msg in all files as well as removed "Docker" word except usage of "docker" client and "Dockerfiles" in the latest PR of 27 Sep ([28b7083] and [826f443]) . This PR is also intended to go into the root OracleTuxedo directory (rather than Archive)  as suggested by you. Could you or the other reviewers please review this whenever you get a chance? Thanks a lot !

**Comment by Djelibeybi** [comment]
Please review the failed checks and update your Markdown and shell scripts so that they pass the lint tests.

**Comment by samil786** [comment]
Deleted Old files and updated new lint checked version

**Comment by Diw-dev** [comment]
The below message from the above "Lint shell scripts" is incorrect. The linter is not able to interpret that setenv.sh was generated in the shell script just a few lines earlier:

```
In /github/workspace/OracleTuxedo22c/samples/ws/wsapp_runme.sh line 37:
source ./setenv.sh
       ^---------^ SC1091 (info): Not following: ./setenv.sh: openBinaryFile: does not exist (No such file or directory)
```

**Comment by Djelibeybi** [comment]
Correct. Please add the appropriate flag to disable that check for those particular lines in the script.

**Comment by Diw-dev** [comment]
Hello Djelibeybi,

Could you please help in closing this PR? I will be applying the link fixes and submitting another PR using my id/repo. Thank you.

**Comment by Djelibeybi** [comment]
Your GitHub account is not yet a member of OGHO. Please resolve that so that the OCA Bot removes its block.

**Comment by Diw-dev** [comment]
Just publicized my membership as detailed in the below link. Hopefully it should resolve the OCA issue. Thanks.

[Publicize your membership as instructed](https://help.github.com/articles/publicizing-or-hiding-organization-membership/)

**Pull request closed without merging**
