### PR TITLE
[OracleRestDataServices] Use custom listen port if specified by PORT env variable

### PR DESCRIPTION
**Pull request by fabiocaseri**
Ability to specify a customizable http listen port using PORT env variable (default remains 8888)

Signed-off-by: Fabio Caseri

### CODE REVIEW

**Comment by gvenzl** [comment]
Thanks a lot @fabiocaseri for the PR. Why do you think it's necessary to change the port inside the container when the mapping can be done to any port anyway?

**Comment by fabiocaseri** [comment]
Agree, not so necessary, just to give freedom of choice.

**Comment by gvenzl** [comment]
You still got the freedom by just saying `docker run ... -p 5432:8888` or `docker run ... -p 1234:8888`. Being able to specify the port inside the container does not provide any additional flexibility nor value. It just increases the complexity as people could pull an image that uses a random port inside the container

**Comment by fabiocaseri** [comment]
Ok, we can close this one.
Thanks!

**Pull request closed without merging**
