### PR TITLE
Provide PowerShell script for Windows platform

### PR DESCRIPTION
**Pull request by fjhorrillo**
Bash script translate to Windows PowerShell

### CODE REVIEW

**Comment by Djelibeybi** [comment]
This will require an OCA, so I'm assigning @brunoborges to handle that, and @gvenzl can review the script itself.

**Comment by fjhorrillo** [comment]
I have added one more script for WebLogic and fixed a bug about reading Checksum file

**Comment by fjhorrillo** [comment]
I have added scripts for OracleJava

**Comment by gvenzl** [comment]
Removing the label `database` as there are more scripts provided now. What I'm unclear, Mac user speaking: Will be a powershell script be enough, just to make building the images easier, or does Windows also require a change of the Dockerfiles themselves. I.e. right now this is running under the Linux 7 slim image. Do we need to use a Windows image and install the Windows based Database binaries?

**Comment by fjhorrillo** [comment]
Hi gvenzl, my scripts allow user to build the same as in Linux (using Linux containers) with the same syntax but from Windows (I tested it on Windows 10).
Other option is what you mean, using nanoserver (Windows Server 2016 nano image) instead of Linux but for that it is necessary to change the Dockerfiles and the result would no longer be the same images, it will be the equivalent in the Windows platform.

**Comment by gvenzl** [comment]
Thanks a lot for the clarification, @fjhorrillo

**Comment by brunoborges** [comment]
@Djelibeybi @gvenzl I can't review/test/maintain these scripts. Can some of you? If we can't find someone in our group to do that, I'm afraid we won't be able to take these in

**Comment by Djelibeybi** [comment]
@brunoborges I don't have access to any Windows systems. I cannot review/test/maintain these scripts.

**Comment by Djelibeybi** [comment]
I'm closing this PR due to lack of activity and lack of internal access to Windows for QA purposes.

**Pull request closed without merging**
