### PR TITLE
Minor fixes to get 12.2.0.1 working

### PR DESCRIPTION
**Pull request by r2datical**
* Updated buildDockerImage.sh to reflect the dir's in the repos.
* Moved Dockerfile to Dockerfile.ee and copied to Dockerfile.se2. Figured that would be better than updating buildDockerImage.sh for 12.2.0.1

### CODE REVIEW

**Comment by r2datical** [comment]
I have completed the ORA and submitted it via email.

**Comment by Djelibeybi** [comment]
@gvenzl I have verified the OCA. Please go ahead and review this pull request.

**Comment by gvenzl** [comment]
Hi @r2datical!

First of all, thanks a lot for your contribution, it is highly appreciated!

I struggle to understand the intention of this PR.
It seems that the PR is to provide the capability to build Oracle Database 12.2.0.1 SE2 Docker images. This, however, is already possible with the current files and controlled via the `-s` and `-e` parameters of the `buildDockerImage.sh` script:

## Building the EE image:

```
[oracle@ol7 dockerfiles]$ ./buildDockerImage.sh -e -v 12.2.0.1
Checking Docker version.
Checking if required packages are present and valid...
linuxx64_12201_database.zip: OK
...
...
...
Successfully built 944bdb5d030b
Successfully tagged oracle/database:12.2.0.1-ee


  Oracle Database Docker Image for 'ee' version 12.2.0.1 is ready to be extended:

    --> oracle/database:12.2.0.1-ee

  Build completed in 605 seconds.
```

```
[oracle@ol7 dockerfiles]$ docker run --name ee oracle/database:12.2.0.1-ee
ORACLE PASSWORD FOR SYS, SYSTEM AND PDBADMIN:
...
...
...
SQL*Plus: Release 12.2.0.1.0 Production on Thu Mar 12 22:26:38 2020

Copyright (c) 1982, 2016, Oracle.  All rights reserved.


Connected to:
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

SQL>
System altered.

SQL>
Pluggable database altered.

SQL>
PL/SQL procedure successfully completed.

SQL> Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
The Oracle base remains unchanged with value /opt/oracle
#########################
DATABASE IS READY TO USE!
#########################
```

--> Connected to: Oracle Database 12c **Enterprise Edition** Release 12.2.0.1.0 - 64bit Production

## Building the SE2 image:

```
[oracle@ol7 dockerfiles]$ ./buildDockerImage.sh -s -v 12.2.0.1
Checking Docker version.
Checking if required packages are present and valid...
linuxx64_12201_database.zip: OK
...
...
...
Successfully built b71668d2754c
Successfully tagged oracle/database:12.2.0.1-se2


  Oracle Database Docker Image for 'se2' version 12.2.0.1 is ready to be extended:

    --> oracle/database:12.2.0.1-se2

  Build completed in 574 seconds.
```

```
[oracle@ol7 dockerfiles]$ ./buildDockerImage.sh -s -v 12.2.0.1
Checking Docker version.
Checking if required packages are present and valid...
linuxx64_12201_database.zip: OK
...
...
...
SQL*Plus: Release 12.2.0.1.0 Production on Thu Mar 12 22:36:30 2020

Copyright (c) 1982, 2016, Oracle.  All rights reserved.


Connected to:
Oracle Database 12c Standard Edition Release 12.2.0.1.0 - 64bit Production

SQL>
System altered.

SQL>
Pluggable database altered.

SQL>
PL/SQL procedure successfully completed.

SQL> Disconnected from Oracle Database 12c Standard Edition Release 12.2.0.1.0 - 64bit Production
The Oracle base remains unchanged with value /opt/oracle
#########################
DATABASE IS READY TO USE!
#########################
```

--> Connected to: Oracle Database 12c **Standard Edition** Release 12.2.0.1.0 - 64bit Production

**Comment by r2datical** [comment]
Ha! So, weird...thanks for setting me straight. I SWEAR I was trying to do just that but ran into problems. I'm going to close this,

Thanks a ton for looking at it!!! Big fan of you and team's work!!!

**Comment by gvenzl** [comment]
No worries, I was just not sure whether I was missing something or not.
Perhaps you had the wrong zip file in the directory or similar...

Glad to read that it works now!

**Pull request closed without merging**
