### PR TITLE
Replacing yum clean all across the repo

### LINKED ISSUE #555: Oracle 12.2.0.1 EE Dockerfile build points at cleanup tip for yum install
I was watching the Docker build for oracle/database:12.2.0.1-ee, and noticed that it mentioned something that wasn't being done in between steps 7 and 8:

```sh
...  
  systemd.x86_64 0:219-42.0.1.el7
  systemd-libs.x86_64 0:219-42.0.1.el7
  systemd-sysv.x86_64 0:219-42.0.1.el7
  sysvinit-tools.x86_64 0:2.88-14.dsf.el7
  tcp_wrappers.x86_64 0:7.6-77.el7
  tcp_wrappers-libs.x86_64 0:7.6-77.el7
  util-linux.x86_64 0:2.23.2-43.el7
  xorg-x11-utils.x86_64 0:7.5-22.el7
  xorg-x11-xauth.x86_64 1:1.0.9-1.el7
  xz.x86_64 0:5.2.2-1.el7

Complete!
Loaded plugins: ovl
Cleaning repos: ol7_UEKR4 ol7_latest
Cleaning up everything
Maybe you want: rm -rf /var/cache/yum, to also free up space taken by orphaned data from disabled or removed repos
 ---> 8b815822c42e
Removing intermediate container 8adf5f138aad
Step 8/16 : USER oracle
 ---> Running in b0422ea0152e
 ---> 36f2b6902a62
Removing intermediate container b0422ea0152e
Step 9/16 : RUN $INSTALL_DIR/$INSTALL_DB_BINARIES_FILE EE
```

### PR DESCRIPTION
**Pull request by Djelibeybi**
This resolves #555 by replacing all instances of `yum clean all` with `rm -rf /var/cache/yum` as the annoying new message suggests.

I'm going to tag a whole bunch of reviewers for each person to review their own `Dockerfile`.

Signed-off-by: Avi Miller <avi.miller@oracle.com>

### CODE REVIEW

**Comment by sbalousek** [comment]
From what I can gather from the YUM documentation, this change will leave the header files on disk, where as "yum clean all" will remove those header files.

Wouldn't a more correct solution be:

    yum clean headers && rm -fr /var/cache/yum

**Comment by Djelibeybi** [comment]
No, `rm -rf /var/cache/yum` is the massive hammer approach. It removes _all_ `yum` metadata by removing the entire cache hierarchy.

**Comment by brunoborges** [comment]
Avi, do you think we could have a base #Docker file with some ONBUILD instructions?

**Comment by Djelibeybi** [comment]
Ok, I believe I have found and removed *all* instances of `yum clean all` now. :)

**Pull request merged**
