### PR TITLE
Fix wrong license statement

### PR DESCRIPTION
**Pull request by brunoborges**
Files are licensed under UPL.

### CODE REVIEW

**Comment by Djelibeybi** [comment]
If all the content is under the UPL, do we really need a LICENSE in every folder? Can't we just have one in the root of the repo?

**Comment by brunoborges** [comment]
We could, but for now each project is still evaluated separately.

**Comment by Djelibeybi** [comment]
In which case, only the projects that _don't_ use the UPL need their own `LICENSE` file.

**Comment by brunoborges** [comment]
Let's merge this PR and then remove repeated files. I really want to get done with this :-)

**Comment by gvenzl** [comment]
Fine by me.

**Pull request merged**
