### PR TITLE
Fix for #169 & #141

### PR DESCRIPTION
**Pull request by gvenzl**
Proxy settings build arguments where passed incorrectly

### CODE REVIEW

**Comment by ramonPires** [comment]
@gvenzl , https://github.com/oracle/docker-images/pull/170/commits/2b573682d514d858f19386dc5172342af212c454 , only oracle 12.1.0.2 will be persisted?

**Comment by ramonPires** [comment]
@gvenzl I asked about oracle 12.1.0.2  because the folder structures on Oracle XE is different. Is a problem to change Oracle XE to persisted?

**Comment by gvenzl** [comment]
Hey @ramonPires That is correct, these changes are only for 12.1.0.2 EE and SE2. XE is underway (the installation is, as you pointed out a bit different for XE).

**Comment by gvenzl** [comment]
And now we got XE too :)

**Comment by gvenzl** [comment]
Hey @brunoborges, can you just have a quick look over the changes and sign off before we merge them back.

**Comment by ramonPires** [comment]
@gvenzl thank you!

**Comment by gvenzl** [comment]
@ramonPires Feel free to test the changes and let me know.

**Comment by ramonPires** [comment]
I tested with docker for mac `1.12.2-rc1` and creating an Oracle XE container and work perfectly. Finally, I can work with oracle database on my machine, thank you again @gvenzl .

**Comment by gvenzl** [comment]
I'm very glad to hear, @ramonPires Just FYI, if you just want to use the image for development on your laptop, you can also use the 12c SE or EE versions from [Oracle Technology Network](http://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html).

**Comment by ramonPires** [comment]
@gvenzl the only problem for me with 12c SE or EE is because the image size is bigger than the XE image. Anyway, is good to know.

**Comment by xploreraj** [comment]
@gvenzl @ramonPires Can you tell me how to persist so that data remains on docker stop and restart.
I am using this command in mac: `docker run --name OracleXE --shm-size=1g -p 1521:1521 -p 8080:8080 -e ORACLE_PWD=password oracle/database:11.2.0.2-xe`

**Comment by xploreraj** [comment]
Thanks @ramonPires . It worked. Its persisting now.

**Pull request merged**
