### PR TITLE
feat: add Oracle DB enabled PHP 7.4 images based on Oracle Linux 8

### PR DESCRIPTION
**Pull request by Djelibeybi**
@cjbj could you please [test the images built over in my fork](https://github.com/Djelibeybi/docker-images/pkgs/container/oraclelinux8-php) to make sure everything works as expected?

Signed-off-by: Avi Miller <avi.miller@oracle.com>

### CODE REVIEW

**Comment by Djelibeybi** [comment]
@AmedeeBulle @totalamateurhour can you please approve this?

**Review by totalamateurhour — APPROVED** [review]
LGTM

**Comment by cjbj** [comment]
@Djelibeybi I thought the FPM mode container was broken, as we discussed on Slack?

**Comment by Djelibeybi** [comment]
It works just fine if you connect to it using FastCGI.

**Comment by cjbj** [comment]
Send me the steps!

**Comment by Djelibeybi** [comment]
https://www.gregfreeman.io/2016/how-to-connect-to-php-fpm-directly-to-resolve-issues-with-blank-pages/

**Pull request merged**
